dist: focal

language: minimal

stages:
  - lint
  - test
  - deploy

if: branch = master OR type = pull_request

before_install:
  - tmpdaemon=$(mktemp)
  - sudo jq '."registry-mirrors" += ["https://mirror.gcr.io"]' /etc/docker/daemon.json > "$tmpdaemon"
  - sudo mv "$tmpdaemon" /etc/docker/daemon.json
  - sudo systemctl daemon-reload
  - sudo systemctl restart docker
  - docker system info

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script:
        - make docker/run target=lint
    - stage: test
      name: Run unit and integration tests against a mock AWS stack
      install:
        - make docker-compose/install
      script: 
        - make docker/run target=pytest/lambda/tests
        - make mockstack/up
        - make mockstack/pytest/lambda
      after_script:
        - make mockstack/clean
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/terraform-aws-org-new-account-trust-policy
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [terraform-aws-org-new-account-trust-policy v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/terraform-aws-org-new-account-trust-policy/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: QqpzgPcRKCBmycYwplBarRMOP7D5xFpxJjiEe6oIoWnCyeRJ8u2rxXUmfvQndqqZQKUPO2Bvaw6b5Tq4Rmb9BSws0S4Vb4AWQzSRn0IQquDsePyl/BTdHZhtF/NP9Pkn+sPjYnAjcX+SCvTRcv5INUTQYd/ryjUR1omXV+T85s+hx7C165//14eTULr/gNImaOdZPN6C7cPmBqvV/+Sx/Vg/zUaZm4hWu9Ik4hTvCOQ/HPR+N0SMA70KFdPxW491NFddGsd+nmtskQNbdfn52+aTzE/Efyr3GDtHTFowjmX9rxlMxS6GI6LmJOEK6OYrc8MMbJ+P3MkM3TgPXtdNW1aiHvE+8Av9A6q8P8mOgZW/8M+AExy5xbvrUF7RbJaYc5LLoiBl/Tb+wpHw1gQlMSLzlO2cc54SX91V2fgbGeTyqOtmfpPf1851o8L4cIrw3vbDNisrjIzv94edvxg+UfqJbkhkhe9PXxRWNRQILNVYl3ZaJdBtmSFZottXGai45FlH/17D/I3pFr10BsUyDa0AmqlnokSz5lepmfxInBSuHGfXabVELcgcR5qVpS6p/lT0PcHP3IcfVVGNEaU5HBpuH8Ohv7ZC9mUpijzUuZcMaenrjiUnblyZabxNOHhl+c6Wo0TXTFtFFWT58Bag8t7CjZQLqnFhNau3zNpYj1U=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/terraform-aws-org-new-account-trust-policy
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
