name: Run test jobs
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: MetroStar/actions-workflows/.github/workflows/test.yml@93a9326e07945e5441d0fadef735563290edd729

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this git repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Run python lambda unit tests
        run: make docker/run target=pytest/lambda/tests
